version: '3'
services:
  web:
    image: node:21 
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/frontend 
    command: >
      bash -c "
      cd frontend &&
      npm install && npm run build &&
      npm install -g serve &&
      serve -s build
      "

  flask:
    image: python:3.11 
    ports:
      - "666:666" # hostport:containerport
    volumes:
      - ./backend:/backend 
    command:  >
      bash -c "
      cd backend && 
      pip install -r requirements.txt &&
      python3 app/manager.py
      "
    environment:
      - PYTHONUNBUFFERED=1
